services:
  - type: web
    name: canyon-concierge-prototype
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
    autoDeploy: true
